import UIKit

public enum Images {
  public static let arrowLeft = UIImage(named: "arrow.left", in: Bundle.module, with: nil)
  public static let arrowRight = UIImage(named: "arrow.right", in: Bundle.module, with: nil)
  public static let chevronDown = UIImage(named: "chevron.down", in: Bundle.module, with: nil)
  public static let chevronLeft = UIImage(named: "chevron.left", in: Bundle.module, with: nil)
  public static let chevronRight = UIImage(named: "chevron.right", in: Bundle.module, with: nil)
  
  public static let mongClubFill = UIImage(named: "mong.club.fill", in: Bundle.module, with: nil)
  public static let mongClub = UIImage(named: "mong.club", in: Bundle.module, with: nil)
  public static let mongCongrats = UIImage(named: "mong.congrats", in: Bundle.module, with: nil)
  public static let mongEditorFill = UIImage(named: "mong.editor.fill", in: Bundle.module, with: nil)
  public static let mongEditor = UIImage(named: "mong.editor", in: Bundle.module, with: nil)
  public static let mongLedger = UIImage(named: "mong.ledger", in: Bundle.module, with: nil)
  public static let mong = UIImage(named: "mong", in: Bundle.module, with: nil)
  public static let mongPass = UIImage(named: "mong.pass", in: Bundle.module, with: nil)
  public static let mongPassNot = UIImage(named: "mong.pass.not", in: Bundle.module, with: nil)
  public static let mongGray = UIImage(named: "mong.gray", in: Bundle.module, with: nil)
  public static let mongStudy = UIImage(named: "mong.study", in: Bundle.module, with: nil)
  public static let mongBackgroundCircle = UIImage(named: "mong.background.circle", in: Bundle.module, with: nil)
  public static let mongSplash = UIImage(named: "mong.splash", in: Bundle.module, with: nil)
  public static let mongCode = UIImage(named: "mong.code", in: Bundle.module, with: nil)
  public static let mongParty = UIImage(named: "mong.party", in: Bundle.module, with: nil)
  public static let mongLedgerEmpty = UIImage(named: "mong.ledger.empty", in: Bundle.module, with: nil)
  public static let mongInquiry = UIImage(named: "mong.inquiry", in: .module, with: nil)
  
  public static let scanPhone = UIImage(named: "scan.phone", in: Bundle.module, with: nil)
  public static let accountRecord = UIImage(named: "accountRecord", in: Bundle.module, with: nil)
  public static let agency = UIImage(named: "agency", in: Bundle.module, with: nil)
  public static let agencyCongrats = UIImage(named: "agency.congrats", in: Bundle.module, with: nil)
  
  public static let check = UIImage(named: "check", in: Bundle.module, with: nil)
  public static let checkboxCheck = UIImage(named: "checkbox.check", in: Bundle.module, with: nil)
  public static let checkboxFill = UIImage(named: "checkbox.fill", in: Bundle.module, with: nil)
  public static let checkbox = UIImage(named: "checkbox", in: Bundle.module, with: nil)
  public static let closeFill = UIImage(named: "close.fill", in: Bundle.module, with: nil)
  public static let close = UIImage(named: "close", in: Bundle.module, with: nil)
  public static let copy = UIImage(named: "copy", in: Bundle.module, with: nil)
  public static let document = UIImage(named: "document", in: Bundle.module, with: nil)
  public static let hamburg = UIImage(named: "hamburg", in: Bundle.module, with: nil)
  public static let intive = UIImage(named: "intive", in: Bundle.module, with: nil)
  public static let logout = UIImage(named: "logout", in: Bundle.module, with: nil)
  public static let money = UIImage(named: "money", in: Bundle.module, with: nil)
  public static let more = UIImage(named: "more", in: Bundle.module, with: nil)
  public static let paper = UIImage(named: "paper", in: Bundle.module, with: nil)
  public static let pencil = UIImage(named: "pencil", in: Bundle.module, with: nil)
  public static let pencilGray = UIImage(named: "pencil.gray", in: Bundle.module, with: nil)
  public static let photo = UIImage(named: "photo", in: Bundle.module, with: nil)
  public static let plan = UIImage(named: "plan", in: Bundle.module, with: nil)

  public static let record = UIImage(named: "record", in: Bundle.module, with: nil)
  public static let reissue = UIImage(named: "reissue", in: Bundle.module, with: nil)
  public static let scan = UIImage(named: "scan", in: Bundle.module, with: nil)
  public static let schoolBlue = UIImage(named: "school.blue", in: Bundle.module, with: nil)
  public static let school = UIImage(named: "school", in: Bundle.module, with: nil)
  public static let search = UIImage(named: "search", in: Bundle.module, with: nil)
  public static let hexagon = UIImage(named: "hexagon", in: Bundle.module, with: nil)
  public static let time = UIImage(named: "time", in: Bundle.module, with: nil)
  public static let trash = UIImage(named: "trash", in: Bundle.module, with: nil)
  public static let university = UIImage(named: "university", in: Bundle.module, with: nil)
  public static let kakaoTalk = UIImage(named: "kakaoTalk", in: Bundle.module, with: nil)
  public static let apple = UIImage(named: "apple", in: Bundle.module, with: nil)
  public static let congrats = UIImage(named: "congrats", in: Bundle.module, with: nil)
  
  
  public static let closeCircleFill = UIImage(named: "close.circle.fill", in: Bundle.module, with: nil)
  public static let plusCircleFillGreen = UIImage(named: "plus.circle.fill.green", in: Bundle.module, with: nil)
  public static let plusCircleFillRed = UIImage(named: "plus.circle.fill.red", in: Bundle.module, with: nil)
  public static let plusCircleFillBlue = UIImage(named: "plus.circle.fill.blue", in: Bundle.module, with: nil)

  public static let pencilCircleFill = UIImage(named: "pencil.circle.fill", in: Bundle.module, with: nil)
  public static let scanCircleFill = UIImage(named: "scan.circle.fill", in: Bundle.module, with: nil)
  public static let warningFill = UIImage(named: "warning.fill", in: Bundle.module, with: nil)
  public static let warning = UIImage(named: "warning", in: Bundle.module, with: nil)
 

  public static let kakaoLogo = UIImage(named: "kakaoLogo", in: Bundle.module, with: nil)
  public static let appleLogo = UIImage(named: "appleLogo", in: Bundle.module, with: nil)

  public static let cameraShutter = UIImage(named: "camera.shutter", in: Bundle.module, with: nil)
  public static let scanGuide = UIImage(named: "scan.guide", in: Bundle.module, with: nil)
  
  public static let agencyLineBlue = UIImage(named: "agency.line.blue", in: Bundle.module, with: nil)
  public static let moneyLineBlue = UIImage(named: "money.line.blue", in: Bundle.module, with: nil)
  public static let planLineBlue = UIImage(named: "plan.line.blue", in: Bundle.module, with: nil)
  public static let timeLineBlue = UIImage(named: "time.line.blue", in: Bundle.module, with: nil)
  
  public static let feedback = UIImage(named: "feedback", in: Bundle.module, with: nil)
}

