import UIKit

public enum Images {
  public static var arrowLeft = UIImage(named: "arrow.left")
  public static var arrowRight = UIImage(named: "arrow.right")
  public static var chevronDown = UIImage(named: "chevron.down")
  public static var chevronLeft = UIImage(named: "chevron.left")
  public static var chevronRight = UIImage(named: "chevron.right")
  
  public static var mongClubFill = UIImage(named: "mong.club.fill")
  public static var mongCongrats = UIImage(named: "mong.congrats")
  public static var mongEditorFill = UIImage(named: "mong.editor.fill")
  public static var mongEditor = UIImage(named: "mong.editor")
  public static var mongGroup = UIImage(named: "mong.group")
  public static var mong = UIImage(named: "mong")
  public static var mongPass = UIImage(named: "mong.pass")
  public static var mongPassNot = UIImage(named: "mong.pass.not")
  
  public static var accountRecord = UIImage(named: "accountRecord")
  public static var agencyGray = UIImage(named: "agency.gray")
  public static var agency = UIImage(named: "agency")
  public static var camera = UIImage(named: "camera")
  public static var check = UIImage(named: "check")
  public static var checkboxCheck = UIImage(named: "checkbox.check")
  public static var checkboxFill = UIImage(named: "checkbox.fill")
  public static var checkbox = UIImage(named: "checkbox")
  public static var closeFill = UIImage(named: "close.fill")
  public static var close = UIImage(named: "close")
  public static var congrats = UIImage(named: "congrats")
  public static var copy = UIImage(named: "copy")
  public static var document = UIImage(named: "document")
  public static var hamburg = UIImage(named: "hamburg")
  public static var infoFill = UIImage(named: "info.fill")
  public static var info = UIImage(named: "info")
  public static var intive = UIImage(named: "intive")
  public static var logout = UIImage(named: "logout")
  public static var money = UIImage(named: "money")
  public static var more = UIImage(named: "more")
  public static var paper = UIImage(named: "paper")
  public static var pencil = UIImage(named: "pencil")
  public static var photo = UIImage(named: "photo")
  public static var plan = UIImage(named: "plan")
  public static var plusCircleFill = UIImage(named: "plus.circle.fill")
  public static var plusCircle = UIImage(named: "plus.circle")
  public static var plus = UIImage(named: "plus")
  public static var record = UIImage(named: "record")
  public static var reissue = UIImage(named: "reissue")
  public static var scan = UIImage(named: "scan")
  public static var schoolBlue = UIImage(named: "school.blue")
  public static var school = UIImage(named: "school")
  public static var search = UIImage(named: "search")
  public static var time = UIImage(named: "time")
  public static var trash = UIImage(named: "trash")
  public static var university = UIImage(named: "university")
}

