import UIKit

public enum Images {
  public static var arrowLeft = UIImage(named: "arrow.left", in: Bundle.module, with: nil)
  public static var arrowRight = UIImage(named: "arrow.right", in: Bundle.module, with: nil)
  public static var chevronDown = UIImage(named: "chevron.down", in: Bundle.module, with: nil)
  public static var chevronLeft = UIImage(named: "chevron.left", in: Bundle.module, with: nil)
  public static var chevronRight = UIImage(named: "chevron.right", in: Bundle.module, with: nil)
  
  public static var mongClubFill = UIImage(named: "mong.club.fill", in: Bundle.module, with: nil)
  public static var mongCongrats = UIImage(named: "mong.congrats", in: Bundle.module, with: nil)
  public static var mongEditorFill = UIImage(named: "mong.editor.fill", in: Bundle.module, with: nil)
  public static var mongEditor = UIImage(named: "mong.editor", in: Bundle.module, with: nil)
  public static var mongGroup = UIImage(named: "mong.group", in: Bundle.module, with: nil)
  public static var mong = UIImage(named: "mong", in: Bundle.module, with: nil)
  public static var mongPass = UIImage(named: "mong.pass", in: Bundle.module, with: nil)
  public static var mongPassNot = UIImage(named: "mong.pass.not", in: Bundle.module, with: nil)
  public static var mongGray = UIImage(named: "mong.gray", in: Bundle.module, with: nil)
  public static var mongStudy = UIImage(named: "mong.study", in: Bundle.module, with: nil)
  
  public static var accountRecord = UIImage(named: "accountRecord", in: Bundle.module, with: nil)
  public static var agencyGray = UIImage(named: "agency.gray", in: Bundle.module, with: nil)
  public static var agency = UIImage(named: "agency", in: Bundle.module, with: nil)
  public static var camera = UIImage(named: "camera", in: Bundle.module, with: nil)
  public static var check = UIImage(named: "check", in: Bundle.module, with: nil)
  public static var checkboxCheck = UIImage(named: "checkbox.check", in: Bundle.module, with: nil)
  public static var checkboxFill = UIImage(named: "checkbox.fill", in: Bundle.module, with: nil)
  public static var checkbox = UIImage(named: "checkbox", in: Bundle.module, with: nil)
  public static var closeFill = UIImage(named: "close.fill", in: Bundle.module, with: nil)
  public static var close = UIImage(named: "close", in: Bundle.module, with: nil)
  public static var copy = UIImage(named: "copy", in: Bundle.module, with: nil)
  public static var document = UIImage(named: "document", in: Bundle.module, with: nil)
  public static var hamburg = UIImage(named: "hamburg", in: Bundle.module, with: nil)
  public static var intive = UIImage(named: "intive", in: Bundle.module, with: nil)
  public static var logout = UIImage(named: "logout", in: Bundle.module, with: nil)
  public static var money = UIImage(named: "money", in: Bundle.module, with: nil)
  public static var more = UIImage(named: "more", in: Bundle.module, with: nil)
  public static var paper = UIImage(named: "paper", in: Bundle.module, with: nil)
  public static var pencil = UIImage(named: "pencil", in: Bundle.module, with: nil)
  public static var photo = UIImage(named: "photo", in: Bundle.module, with: nil)
  public static var plan = UIImage(named: "plan", in: Bundle.module, with: nil)
  public static var plusCircleFill = UIImage(named: "plus.circle.fill", in: Bundle.module, with: nil)
  public static var plusCircle = UIImage(named: "plus.circle", in: Bundle.module, with: nil)
  public static var plus = UIImage(named: "plus", in: Bundle.module, with: nil)
  public static var record = UIImage(named: "record", in: Bundle.module, with: nil)
  public static var reissue = UIImage(named: "reissue", in: Bundle.module, with: nil)
  public static var scan = UIImage(named: "scan", in: Bundle.module, with: nil)
  public static var schoolBlue = UIImage(named: "school.blue", in: Bundle.module, with: nil)
  public static var school = UIImage(named: "school", in: Bundle.module, with: nil)
  public static var search = UIImage(named: "search", in: Bundle.module, with: nil)
  public static var time = UIImage(named: "time", in: Bundle.module, with: nil)
  public static var trash = UIImage(named: "trash", in: Bundle.module, with: nil)
  public static var university = UIImage(named: "university", in: Bundle.module, with: nil)
  
  public static var closeCircleFill = UIImage(named: "close.circle.fill", in: Bundle.module, with: nil)
  public static var plusCircleFillGreen = UIImage(named: "plus.circle.fill.green", in: Bundle.module, with: nil)
  public static var pencilCircleFill = UIImage(named: "pencil.circle.fill", in: Bundle.module, with: nil)
  public static var scanCircleFill = UIImage(named: "scan.circle.fill", in: Bundle.module, with: nil)
  public static var warningFill = UIImage(named: "warning.fill", in: Bundle.module, with: nil)
  public static var warning = UIImage(named: "warning", in: Bundle.module, with: nil)
  public static var party = UIImage(named: "party", in: Bundle.module, with: nil)

  public static var kakao = UIImage(named: "kakao", in: Bundle.module, with: nil)
  public static var apple = UIImage(named: "apple", in: Bundle.module, with: nil)
}

