name: UploadTestFlight

on:
  push:
    branches: [ develop ]

jobs:
  upload_testflight:
    runs-on: macos_latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15.4.0

      - name: Setting Master Key
        run: | 
          echo "$MASTER_KEY" > Tuist/master.key
        env:
          MASTER_KEY: ${{secrets.MASTER_KEY}}

      - name: Install Tuist
        run: curl -Ls https://install.tuist.io|bash

      - name: Install Fastlane
        run: brew install fastlane
          
      - uses: actions/setup-ruby@v1
        with:
            ruby-version: 2.7
      
      - name: Tuist clean
        run: tuist clean

      - name: Tuist fetch
        run: tuist fetch
      
      - name: Tuist Signing Decrypt
        run: tuist signing decrypt

      - name: Set Keychain
        run: fastlane set_keychain
        env:
            KEYCHAIN_NAME: ${{ secrets.KEYCHAIN_NAME }}
            KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}

      - run: fastlane tf
        env:
            KEYCHAIN_NAME: ${{ secrets.KEYCHAIN_NAME }}
            KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
            APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
            APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
            SLACK_HOOK_URL: ${{ secrets.SLACK_HOOK_URL }}
